spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hehe?useEncoding=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  type-aliases-package: com.xdkj.beans

